name: Build Windows

on:
  push:
    branches:
      - standalone

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run make -- --platform win32

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: out/make/**/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}